prebuilt_cxx_library(
  name = 'rapidjson',
  header_only = True,
  header_namespace = 'rapidjson',
  exported_headers = subdir_glob([
    ('include/rapidjson', '**/*.h'),
  ]),
  visibility = [
    '//...',
  ],
)
