cxx_library(
  name = 'clipper',
  header_namespace = '',
  exported_headers = [
    'clipper.hpp',
  ],
  srcs = [
    'clipper.cpp',
  ],
  licenses = [
    'License.txt',
  ],
  visibility = [
    '//...',
  ],
)
